// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: evalops/v1/judge.proto

package evalopsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	JudgeService_Score_FullMethodName          = "/evalops.v1.JudgeService/Score"
	JudgeService_ScoreBatch_FullMethodName     = "/evalops.v1.JudgeService/ScoreBatch"
	JudgeService_ListJudgeKinds_FullMethodName = "/evalops.v1.JudgeService/ListJudgeKinds"
)

// JudgeServiceClient is the client API for JudgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JudgeService runs rule, LLM-as-a-Judge, and Agent-as-a-Judge scoring on
// (case, sut_output) pairs.  It is a stateless service: the control-plane
// owns persistence and feeds the judge a self-contained ScoreRequest.
//
// The hybrid pipeline (rule -> LLM -> Agent) is implemented server-side so
// the control-plane only has to pick a JudgeConfig and send one request.
type JudgeServiceClient interface {
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	ScoreBatch(ctx context.Context, in *ScoreBatchRequest, opts ...grpc.CallOption) (*ScoreBatchResponse, error)
	ListJudgeKinds(ctx context.Context, in *ListJudgeKindsRequest, opts ...grpc.CallOption) (*ListJudgeKindsResponse, error)
}

type judgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgeServiceClient(cc grpc.ClientConnInterface) JudgeServiceClient {
	return &judgeServiceClient{cc}
}

func (c *judgeServiceClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, JudgeService_Score_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) ScoreBatch(ctx context.Context, in *ScoreBatchRequest, opts ...grpc.CallOption) (*ScoreBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreBatchResponse)
	err := c.cc.Invoke(ctx, JudgeService_ScoreBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) ListJudgeKinds(ctx context.Context, in *ListJudgeKindsRequest, opts ...grpc.CallOption) (*ListJudgeKindsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJudgeKindsResponse)
	err := c.cc.Invoke(ctx, JudgeService_ListJudgeKinds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeServiceServer is the server API for JudgeService service.
// All implementations should embed UnimplementedJudgeServiceServer
// for forward compatibility
//
// JudgeService runs rule, LLM-as-a-Judge, and Agent-as-a-Judge scoring on
// (case, sut_output) pairs.  It is a stateless service: the control-plane
// owns persistence and feeds the judge a self-contained ScoreRequest.
//
// The hybrid pipeline (rule -> LLM -> Agent) is implemented server-side so
// the control-plane only has to pick a JudgeConfig and send one request.
type JudgeServiceServer interface {
	Score(context.Context, *ScoreRequest) (*ScoreResponse, error)
	ScoreBatch(context.Context, *ScoreBatchRequest) (*ScoreBatchResponse, error)
	ListJudgeKinds(context.Context, *ListJudgeKindsRequest) (*ListJudgeKindsResponse, error)
}

// UnimplementedJudgeServiceServer should be embedded to have forward compatible implementations.
type UnimplementedJudgeServiceServer struct {
}

func (UnimplementedJudgeServiceServer) Score(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedJudgeServiceServer) ScoreBatch(context.Context, *ScoreBatchRequest) (*ScoreBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreBatch not implemented")
}
func (UnimplementedJudgeServiceServer) ListJudgeKinds(context.Context, *ListJudgeKindsRequest) (*ListJudgeKindsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJudgeKinds not implemented")
}

// UnsafeJudgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JudgeServiceServer will
// result in compilation errors.
type UnsafeJudgeServiceServer interface {
	mustEmbedUnimplementedJudgeServiceServer()
}

func RegisterJudgeServiceServer(s grpc.ServiceRegistrar, srv JudgeServiceServer) {
	s.RegisterService(&JudgeService_ServiceDesc, srv)
}

func _JudgeService_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_ScoreBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).ScoreBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_ScoreBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).ScoreBatch(ctx, req.(*ScoreBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_ListJudgeKinds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJudgeKindsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).ListJudgeKinds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_ListJudgeKinds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).ListJudgeKinds(ctx, req.(*ListJudgeKindsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JudgeService_ServiceDesc is the grpc.ServiceDesc for JudgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JudgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evalops.v1.JudgeService",
	HandlerType: (*JudgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Score",
			Handler:    _JudgeService_Score_Handler,
		},
		{
			MethodName: "ScoreBatch",
			Handler:    _JudgeService_ScoreBatch_Handler,
		},
		{
			MethodName: "ListJudgeKinds",
			Handler:    _JudgeService_ListJudgeKinds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evalops/v1/judge.proto",
}
