// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: evalops/v1/runner.proto

package evalopsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RunnerService_SubmitRun_FullMethodName       = "/evalops.v1.RunnerService/SubmitRun"
	RunnerService_GetRun_FullMethodName          = "/evalops.v1.RunnerService/GetRun"
	RunnerService_StreamRunEvents_FullMethodName = "/evalops.v1.RunnerService/StreamRunEvents"
	RunnerService_CancelRun_FullMethodName       = "/evalops.v1.RunnerService/CancelRun"
	RunnerService_ListRuns_FullMethodName        = "/evalops.v1.RunnerService/ListRuns"
)

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunnerService is the orchestration surface.  It owns the lifecycle of a
// Run: submit -> enqueue -> stream progress -> finalize -> publish metrics.
// The control-plane calls the eval-engine via this service.
type RunnerServiceClient interface {
	SubmitRun(ctx context.Context, in *SubmitRunRequest, opts ...grpc.CallOption) (*Run, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error)
	StreamRunEvents(ctx context.Context, in *StreamRunEventsRequest, opts ...grpc.CallOption) (RunnerService_StreamRunEventsClient, error)
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) SubmitRun(ctx context.Context, in *SubmitRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, RunnerService_SubmitRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, RunnerService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StreamRunEvents(ctx context.Context, in *StreamRunEventsRequest, opts ...grpc.CallOption) (RunnerService_StreamRunEventsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[0], RunnerService_StreamRunEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &runnerServiceStreamRunEventsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RunnerService_StreamRunEventsClient interface {
	Recv() (*RunEvent, error)
	grpc.ClientStream
}

type runnerServiceStreamRunEventsClient struct {
	grpc.ClientStream
}

func (x *runnerServiceStreamRunEventsClient) Recv() (*RunEvent, error) {
	m := new(RunEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *runnerServiceClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, RunnerService_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, RunnerService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServiceServer is the server API for RunnerService service.
// All implementations should embed UnimplementedRunnerServiceServer
// for forward compatibility
//
// RunnerService is the orchestration surface.  It owns the lifecycle of a
// Run: submit -> enqueue -> stream progress -> finalize -> publish metrics.
// The control-plane calls the eval-engine via this service.
type RunnerServiceServer interface {
	SubmitRun(context.Context, *SubmitRunRequest) (*Run, error)
	GetRun(context.Context, *GetRunRequest) (*Run, error)
	StreamRunEvents(*StreamRunEventsRequest, RunnerService_StreamRunEventsServer) error
	CancelRun(context.Context, *CancelRunRequest) (*Run, error)
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
}

// UnimplementedRunnerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedRunnerServiceServer struct {
}

func (UnimplementedRunnerServiceServer) SubmitRun(context.Context, *SubmitRunRequest) (*Run, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRun not implemented")
}
func (UnimplementedRunnerServiceServer) GetRun(context.Context, *GetRunRequest) (*Run, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedRunnerServiceServer) StreamRunEvents(*StreamRunEventsRequest, RunnerService_StreamRunEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRunEvents not implemented")
}
func (UnimplementedRunnerServiceServer) CancelRun(context.Context, *CancelRunRequest) (*Run, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedRunnerServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRuns not implemented")
}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s grpc.ServiceRegistrar, srv RunnerServiceServer) {
	s.RegisterService(&RunnerService_ServiceDesc, srv)
}

func _RunnerService_SubmitRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).SubmitRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_SubmitRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).SubmitRun(ctx, req.(*SubmitRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StreamRunEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRunEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServiceServer).StreamRunEvents(m, &runnerServiceStreamRunEventsServer{ServerStream: stream})
}

type RunnerService_StreamRunEventsServer interface {
	Send(*RunEvent) error
	grpc.ServerStream
}

type runnerServiceStreamRunEventsServer struct {
	grpc.ServerStream
}

func (x *runnerServiceStreamRunEventsServer) Send(m *RunEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RunnerService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerService_ServiceDesc is the grpc.ServiceDesc for RunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evalops.v1.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitRun",
			Handler:    _RunnerService_SubmitRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _RunnerService_GetRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _RunnerService_CancelRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _RunnerService_ListRuns_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRunEvents",
			Handler:       _RunnerService_StreamRunEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "evalops/v1/runner.proto",
}
